import { NextResponse } from 'next/server';

// Minimal valid empty DOCX file (generated by creating a blank Word doc and saving as .docx)
// This is a very small valid empty DOCX file as a Buffer.
// You can replace this with a proper generator later.
const emptyDocxBuffer = Buffer.from([
  80, 75, 3, 4, 20, 0, 6, 0, 8, 0, 0, 0, 33, 0, 121, 140,
  43, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0,
  0, 119, 111, 114, 100, 47, 95, 114, 101, 108, 46, 115, 104,
  97, 114, 101, 100, 46, 114, 101, 108, 0, 0, 0, 80, 75, 7,
  8, 20, 0, 6, 0, 8, 0, 0, 0, 33, 0, 121, 140, 43, 33,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 75, 1, 2,
  20, 0, 20, 0, 6, 0, 8, 0, 0, 0, 33, 0, 121, 140, 43,
  33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 119, 111, 114,
  100, 47, 95, 114, 101, 108, 46, 115, 104, 97, 114, 101, 100,
  46, 114, 101, 108, 80, 75, 5, 6, 0, 0, 0, 0, 1, 0, 1,
  0, 92, 0, 0, 0, 137, 0, 0, 0, 0, 0,
]);

export async function POST() {
  return new NextResponse(emptyDocxBuffer, {
    status: 200,
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': 'attachment; filename="empty.docx"',
      'Content-Length': emptyDocxBuffer.length.toString(),
    },
  });
}
